name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/d3vi1/*
      GONOSUMDB: github.com/d3vi1/*
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go vet ./...
      - run: go build ./...

  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/d3vi1/*
      GONOSUMDB: github.com/d3vi1/*
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test -race -count=1 ./...

  lint:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/d3vi1/*
      GONOSUMDB: github.com/d3vi1/*
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: golangci/golangci-lint-action@v6
